apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: keeper-cert
    app.kubernetes.io/managed-by: kustomize
  name: keeper-cert
  namespace: default
spec:
  dnsNames:
    - "*.sample-keeper-headless.default.svc"
    - "*.sample-keeper-headless.default.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: local-issuer
  secretName: keeper-cert
---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  replicas: 1
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  settings:
    tls:
      enabled: true
      required: true
      serverCertSecret:
        name: keeper-cert
