apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  replicas: 2
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  keeperClusterRef:
    name: sample
